import Head from 'next/head'
import * as React from 'react';
import Menu from './menu'
import Title from './title'
import Roundbox from './roundbox'
import AddCircleOutlineIcon from '@mui/icons-material/AddCircleOutline';


import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';
import FormControlLabel from '@mui/material/FormControlLabel';
import Radio from '@mui/material/Radio';
import RadioGroup from '@mui/material/RadioGroup';
import Checkbox from '@mui/material/Checkbox';
import Select, { SelectChangeEvent } from '@mui/material/Select';
import styles from '../styles/Home.module.css';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import theme from './api/theme';
import Image from 'next/image';
import Grid from '@mui/material/Grid';
import Button from '@mui/material/Button';
import { style } from '@mui/system';
export default function Home() {

  const [value, setValue] = React.useState('crd');
  const [expanded, setExpanded] = React.useState('crd');
  const handleChange = (event, newExpanded) => {
    setValue((event.target).value);
    setExpanded(newExpanded ? (event.target).value : false);
  };

  const [selectedValue, setSelectedValue] = React.useState('visa');

  const cardChange = (event) => {
    setSelectedValue(event.target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Raza Mobile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <Menu styles={{ height: 100 }}></Menu>
      <main className={styles.main} >
        <Title title="Checkout"></Title>
        <div className={styles.main_inner}>
          <Roundbox>
            <Box >

              <Box
                component="form"
                sx={{
                  pt:5,pr: 5,pl: 5,pb: 0,

                  '& .MuiTextField-root': { m: 1, width: '100%' },
                }}
                noValidate
                autoComplete="off"
              >
                <div className={styles.roundcardTitle}>Billing Details</div>
                <ThemeProvider theme={theme}>
                  <TextField
                    id="firstName"
                    label="First name"
                    variant="standard"
                    style={{ margin: '0px' }}
                  />
                  <TextField
                    id="lastName"
                    label="Last name"
                    variant="standard"
                    style={{ margin: '0px' }}
                  />
                  <TextField
                    id="streetaddress"
                    label="Street address"
                    variant="standard"
                    style={{ margin: '0px' }}
                  />
                  <TextField
                    id="streetaddress"
                    label="Town/ City"
                    variant="standard"
                    style={{ margin: '0px' }}
                  />

                  <FormControl fullWidth variant="standard">
                    <InputLabel id="State-label">State</InputLabel>
                    <Select

                      id="state"
                      value={'SriLanka'}
                      label="State"
                      style={{ margin: '20px 0px 0px 0px' }}


                    >
                      <MenuItem value={'India'}>India</MenuItem>
                      <MenuItem value={'SriLanka'}>SriLanka</MenuItem>
                      <MenuItem value={'US'}>US</MenuItem>
                    </Select>
                  </FormControl>
                  <TextField
                    id="Zip"
                    label="Zip"
                    variant="standard"
                    style={{ margin: '0px' }}
                  />
                  <TextField
                    id="ph"
                    label="Phone number"
                    variant="standard"
                    style={{ margin: '0px' }}
                  />
                  <TextField
                    id="email"
                    label="Email address"
                    variant="standard"
                    style={{ margin: '0px' }}
                  />
                  <FormControlLabel sx={{pt:'10px'}} control={<Checkbox defaultChecked />} label="Ship to billing address" />
                </ThemeProvider>

              </Box>
              <Box className={styles.bb}>

              
              </Box>
              
              <Box sx={{ pt:3,pr: 5,pl: 5,pb: 5, '& .MuiTextField-root': { m: 1, width: '100%', fontWeight: 900 } }}>
              <div className={styles.roundcardTitle}>Shipping Details</div>
                <ThemeProvider theme={theme}>
                  <TextField

                    label="First name"
                    variant="standard"
                    style={{ margin: '0px' }}
                  />
                  <TextField

                    label="Last name"
                    variant="standard"
                    style={{ margin: '0px' }}
                  />
                  <TextField

                    label="Street address"
                    variant="standard"
                    style={{ margin: '0px' }}
                  />
                  <TextField

                    label="Town/ City"
                    variant="standard"
                    style={{ margin: '0px' }}
                  />
                  <TextField

                    label="State"
                    variant="standard"
                    style={{ margin: '0px' }}
                  />
                  <TextField

                    label="Zip"
                    variant="standard"
                    style={{ margin: '0px' }}
                  />
                </ThemeProvider>
              </Box>
            </Box>
          </Roundbox>
          <Roundbox>
            <ThemeProvider theme={theme}>
              <div className={styles.wave}>
                Limited time only FREE shipping
                on the order placed today
              </div>
              <Box className={styles.greyBox}>

                <div><FormControlLabel control={<Checkbox />} label="Auto Renewal" /></div>
                <Box>
                  <Grid container spacing={0}>
                    <Grid item xs={6} styles={{ mt: 10 }}>
                      <div className={styles.fontSize16}>Product</div>
                    </Grid>
                    <Grid item xs={6} sx={{ mb: 2 }}>
                      <div className={styles.fontSize16} style={{ textAlign: 'end' }}>Amount</div>
                    </Grid>
                    <Grid container spacing={0} className={styles.bb} alignItems="center">
                      <Grid item xs={6}>
                        <div className={styles.fontSize38}>15GB <span className={styles.fontSize26}>Plan</span></div>
                        <div className={styles.fontSize25}>3Month-SimKit   2</div>
                      </Grid>
                      <Grid item xs={6} className={styles.push}>
                        <div className={styles.fontSize32} style={{ textAlign: 'end' }}>$150.00</div>
                      </Grid>
                    </Grid>
                    <Grid container spacing={0} className={styles.bb} alignItems="center">
                      <Grid item xs={6}>
                        <div className={styles.fontSize38}>4GB <span className={styles.fontSize26}>Plan</span></div>
                        <div className={styles.fontSize25}>3Month-SimKit     1</div>
                      </Grid>
                      <Grid item xs={6} className={styles.push} style={{ textAlign: 'end' }} >
                        <div className={styles.fontSize32} >$45.00</div>
                      </Grid>
                    </Grid>
                    <Grid container spacing={0} sx={{ mt: '20px' }} alignItems="center">
                      <Grid item xs={6} style={{ alignItems: "self-end" }}>
                        <div className={styles.fontSize18}>Subtotal</div>

                      </Grid>
                      <Grid item xs={6} style={{ textAlign: 'end' }}>
                        <div className={styles.fontSize32} >$195.00</div>
                      </Grid>
                    </Grid>
                  </Grid>
                </Box>
              </Box>
              <Box sx={{ pl: 5,pr:5 }}>
                <Grid container spacing={0} item xs={12} direction="row"
                  justifyContent="space-between" >
                  <Grid container xs={12} className={styles.accordion}>
                    <Grid item xs={6}>

                      <div className={styles.fontSize18+' '+styles.fontBold}>Shipping</div>

                    </Grid>
                    <Grid item xs={6}>
                      <Box style={{ marginRight: 'auto' }}>
                        <RadioGroup row name="row-radio-buttons-group">
                          <div><FormControlLabel value="normal" control={<Radio sx={{
                            color: "##CA0177",
                            padding: 1,
                            '&.Mui-checked': {
                              color: "#CA0177",
                            },
                          }} />} label="3-5 Day Shipping: $0" /></div>
                          <div><FormControlLabel value="Fed" control={<Radio sx={{
                            color: "##CA0177",
                            padding: 1,
                            '&.Mui-checked': {
                              color: "#CA0177",
                            },
                          }} />} label="FedEx Next Day Air : $15" /></div>
                        </RadioGroup>
                      </Box>
                    </Grid>
                  </Grid>
                  <Grid container spacing={0} className={styles.accordion}>
                    <Grid item xs={6}>
                      <div className={styles.fontSize18}>Recovery FREE</div>

                    </Grid>
                    <Grid item xs={6} style={{ textAlign: "right" }}>
                      <div className={styles.fontSize24}>$19.39</div>
                    </Grid>
                  </Grid>
                  <Grid container spacing={0} className={styles.accordion}>
                    <Grid item xs={6}>
                      <div className={styles.fontSize18}>Taxes & Surcharges</div>

                    </Grid>
                    <Grid item xs={6} style={{ textAlign: "right" }}>
                      <div className={styles.fontSize24}>$3.19</div>
                    </Grid>
                  </Grid>
                  <Grid container spacing={0} sx={{ mt: '20px' }} direction={'column'} >
                    <Grid item xs={6} style={{ color: "#CA0177" }} className={styles.fontSize24} >
                      Total
                    </Grid>
                    <Grid item xs={6} style={{ color: "#CA0177", textAlign: "right" }} className={styles.fontSize32}>
                      $232.58
                    </Grid>
                  </Grid>
                </Grid>
              </Box>
              <Box className={styles.greyBox_bt}>
                <Box sx={{ pb: "2rem" }} className={styles.accordion}>
                  <div  className={styles.fontSize20}>Payment Method</div>
                </Box>
                <Grid container className={styles.accordion} spacing={0} alignItems="center" justifyContent="center">

                  <Grid container xs={6} alignItems="center" justifyContent="left">
                    <Grid item> <Radio
                      checked={value === 'crd'}
                      onChange={handleChange}
                      value="crd"
                      name="radio-buttons"
                      inputProps={{ 'aria-label': 'A' }}
                    /></Grid>
                    <Grid item><Image src="/../public/crd.png" width="38" height="34" /></Grid>
                    <Grid item sx={{pl:'10px'}}>Credit Card</Grid>
                  </Grid>

                  <Grid item xs={6}>

                    <Image src="/../public/ccard.png" width="185" height="27" />
                  </Grid>

                  {expanded == "crd" ? <Grid container direction="column" spacing={0} sx={{ ml: "2.5rem", mr: "2.5rem" }}>

                    <Box sx={{ pb: "1rem",pt: "2rem" }} className={styles.fontSize16_black}>Your Saved Credit Cards</Box>
                    <Grid container xs={12} alignItems="center" className={styles.accordion}>
                      <Grid item xs={1}><Image src="/../public/master.png" width='35' height='25' /></Grid>
                      <Grid item xs={5} sx={{pl:'50px'}}>
                        <Box className={styles.fontSize14}>Card Number</Box>
                        <Box>5241 ….8333</Box>
                      </Grid>
                      <Grid item xs={3}>
                        <Box className={styles.fontSize14}>Expires On</Box>
                        <Box>502/23</Box>
                      </Grid>
                      <Grid item xs={1} className={styles.push}>
                        <Box xs={1} ><Radio name="saved-crd" checked={selectedValue === 'master'}  onChange={cardChange}  value="master"  label="" /></Box>
                      </Grid>
                    </Grid>
                    <Grid container xs={12} alignItems="center" justifyContent="left" className={styles.accordion}>
                      <Grid item xs={1}><Image src="/../public/visa.png" width='40' height='13' /></Grid>
                      <Grid item xs={5} sx={{pl:'50px'}}>
                        <Box className={styles.fontSize14}>Card Number</Box>
                        <Box>5241 ….8333</Box>
                      </Grid>
                      <Grid item xs={3}>
                        <Box className={styles.fontSize14}>Expires On</Box>
                        <Box>502/23</Box>
                      </Grid>
                      <Grid item xs={1} className={styles.push}>
                        <Box><Radio name="saved-crd" checked={selectedValue === 'visa'} onChange={cardChange} value="visa" label="" /></Box>
                      </Grid>
                    </Grid>
                    <Box sx={{ pb: "0rem",pt: "1rem" }}>
                      <Button variant="contained" disableElevation
                        sx={{
                          fontSize: 15,
                          pl: 0.8,
                          pr: 2,
                          pb: 0.3,
                          pt: 0.2,
                          flexGrow: 1,
                          backgroundColor: '#CA0177',
                          borderRadius: 28,
                          textTransform: 'capitalize',
                          '&:focus': {
                            outline: 'none',
                            boxShadow: '0 0 0 5px rgba(21, 156, 228, 0.4)'
                          },
                          'svg': {
                            fontSize: 24
                          }

                        }}
                        startIcon={<AddCircleOutlineIcon className={styles.addIcon} />}
                      >
                        Add New Credit Card
                      </Button>
                    </Box>
                  </Grid> : null}
                </Grid>

                <Grid container spacing={0} alignItems="center" className={styles.accordion}>
                  <Grid item xs={6} container alignItems="center" justifyContent="left">
                    <Grid item> <Radio
                      checked={value === 'apple'}
                      onChange={handleChange}
                      value="apple"
                      name="radio-buttons"
                      inputProps={{ 'aria-label': 'apple' }}
                    /></Grid>
                    <Grid item><Image src="/../public/apple-icon.png" width="29" height="36" /></Grid>
                    <Grid item sx={{pl:'10px'}}>Apple</Grid>
                  </Grid>
                  {expanded == "apple" ? <Grid container spacing={0}>
                    <Box>apple pay UI</Box>
                  </Grid> : null}
                </Grid>

                <Grid container spacing={0} alignItems="center" className={styles.accordion}>
                  <Grid item xs={6} container alignItems="center" justifyContent="left">
                    <Grid item> <Radio
                      checked={value === 'paypal'}
                      onChange={handleChange}
                      value="paypal"
                      name="radio-buttons"
                      inputProps={{ 'aria-label': 'paypal' }}
                    /></Grid>
                    <Grid item><Image src="/../public/paypal.png" width="31" height="36" /></Grid>
                    <Grid item sx={{pl:'10px'}}>Paypal</Grid>
                  </Grid>
                  {expanded == "paypal" ? <Grid container spacing={0}>
                    <Box>paypal pay UI</Box>
                  </Grid> : null}
                </Grid>

                <Grid container spacing={0} alignItems="center" className={styles.accordion}>
                  <Grid item xs={6} container alignItems="center" justifyContent="left">
                    <Grid item> <Radio
                      checked={value === 'google'}
                      onChange={handleChange}
                      value="google"
                      name="radio-buttons"
                      inputProps={{ 'aria-label': 'google' }}
                    /></Grid>
                    <Grid item><Image src="/../public/google.png" width="36" height="36" /></Grid>
                    <Grid item sx={{pl:'10px'}}>Google</Grid>
                  </Grid>
                  {expanded == "google" ? <Grid container spacing={0}>
                    <Box>google pay UI</Box>
                  </Grid> : null}
                </Grid>

                <Box sx={{ display: 'flex', mt: "2rem" }}>
                  <Button variant="contained" disableElevation
                    sx={{
                      fontSize: 18,
                      padding: 1.2,
                      flexGrow: 1,
                      backgroundColor: '#6633B5',
                      borderRadius: 28,
                      '&:focus': {
                        outline: 'none',
                        boxShadow: '0 0 0 5px rgba(21, 156, 228, 0.4)'
                      }

                    }}
                  >
                    Proceed to Checkout
                  </Button>
                </Box>



              </Box>
            </ThemeProvider>
          </Roundbox>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
